### ISSUE TITLE
The bot does not work from the word at all

### ISSUE THREAD

**Issue by vsecoder-old-account** [karipov/creationDate#8]
1. The bot does not work from the word at all
2. Share the data file.json, and then the latest version that I could find is not very accurate

Thank you in advance)))

**Comment by karipov** [comment]
I'm afraid the `data.json` file I use has data from users which would not like their IDs disclosed. I'm sorry! You could crowdsource the data by asking family friends and others for their account creation dates. There are other methods to accomplish this as well, please let me know if you'd like to learn how!
